export const daoAbi = [
	{ type: "constructor", inputs: [], stateMutability: "nonpayable" },
	{ type: "receive", stateMutability: "payable" },
	{
		type: "function",
		name: "activities",
		inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		outputs: [
			{ name: "id", type: "uint256", internalType: "uint256" },
			{ name: "organizer", type: "address", internalType: "address" },
			{ name: "activityType", type: "string", internalType: "string" },
			{ name: "fundingGoal", type: "uint256", internalType: "uint256" },
			{
				name: "currentFunding",
				type: "uint256",
				internalType: "uint256",
			},
			{ name: "isVerified", type: "bool", internalType: "bool" },
			{ name: "fundsDelegated", type: "bool", internalType: "bool" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "createActivity",
		inputs: [
			{ name: "_activityType", type: "string", internalType: "string" },
			{ name: "_fundingGoal", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "decrement",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "delegateFunds",
		inputs: [{ name: "_activityId", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "donate",
		inputs: [{ name: "_activityId", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "payable",
	},
	{
		type: "function",
		name: "getActivity",
		inputs: [{ name: "_activityId", type: "uint256", internalType: "uint256" }],
		outputs: [
			{ name: "organizer", type: "address", internalType: "address" },
			{ name: "activityType", type: "string", internalType: "string" },
			{ name: "fundingGoal", type: "uint256", internalType: "uint256" },
			{
				name: "currentFunding",
				type: "uint256",
				internalType: "uint256",
			},
			{ name: "isVerified", type: "bool", internalType: "bool" },
			{ name: "fundsDelegated", type: "bool", internalType: "bool" },
		],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getCount",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "getDonation",
		inputs: [
			{ name: "_activityId", type: "uint256", internalType: "uint256" },
			{ name: "_donor", type: "address", internalType: "address" },
		],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "increment",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "owner",
		inputs: [],
		outputs: [{ name: "", type: "address", internalType: "address" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "reset",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "totalActivities",
		inputs: [],
		outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
		stateMutability: "view",
	},
	{
		type: "function",
		name: "verifyActivity",
		inputs: [{ name: "_activityId", type: "uint256", internalType: "uint256" }],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "withdrawEmergency",
		inputs: [],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "event",
		name: "ActivityCreated",
		inputs: [
			{
				name: "id",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "organizer",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "activityType",
				type: "string",
				indexed: false,
				internalType: "string",
			},
			{
				name: "fundingGoal",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "ActivityVerified",
		inputs: [
			{
				name: "id",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "CountUpdated",
		inputs: [
			{
				name: "newCount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "DonationReceived",
		inputs: [
			{
				name: "id",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "donor",
				type: "address",
				indexed: true,
				internalType: "address",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "EmergencyWithdraw",
		inputs: [
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{
		type: "event",
		name: "FundsDelegated",
		inputs: [
			{
				name: "id",
				type: "uint256",
				indexed: true,
				internalType: "uint256",
			},
			{
				name: "amount",
				type: "uint256",
				indexed: false,
				internalType: "uint256",
			},
		],
		anonymous: false,
	},
	{ type: "error", name: "AlreadyVerified", inputs: [] },
	{ type: "error", name: "FundingGoalNotReached", inputs: [] },
	{ type: "error", name: "FundsAlreadyDelegated", inputs: [] },
	{ type: "error", name: "InvalidActivity", inputs: [] },
	{ type: "error", name: "InvalidAmount", inputs: [] },
	{ type: "error", name: "TransferFailed", inputs: [] },
	{ type: "error", name: "Unauthorized", inputs: [] },
] as const;
