nodeLinker: node-modules

npmRegistries:
  "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/":
    npmAuthToken: "NpmToken.f7bcd249-9f95-3c73-a5b2-86b3c5b7276c"

npmScopes:
  codefi:
    npmRegistryServer: "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/"
